project:
  type: website
  output-dir: docs

website:
  title: "EpiEvidence"

  navbar:
    logo: Logo_only.png

    right:
      - text: Home
        href: index.qmd

      - text: Epidemiology
        href: epidemiology.qmd

      - text: Data Science
        href: datascience.qmd

      - text: Insights
        href: insights.qmd

      - text: Publications
        href: publications.qmd

      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false